//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPiSoution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        public int AccountID { get; set; }
        public int AccountNumber { get; set; }
        public string AccountsHolderName { get; set; }
        public string AccountType { get; set; }
        public decimal CurrentBalance { get; set; }
        public Nullable<System.DateTime> AccountOpeningDate { get; set; }
    }
}
